services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - coderunner-logs:/var/log/nginx
    depends_on:
      - front
      - auth
      - gorunner
      - pyrunner
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: coderunner
    volumes:
      - coderunner-data:/var/lib/postgresql/data
    networks:
      - app_network

  front:
    container_name: front
    build:
      context: frontend
      dockerfile: Dockerfile
      args: 
        MODE: development
    depends_on:
      - gorunner
      - pyrunner
      - auth
    networks:
      - app_network
    develop:
      watch: 
        - path: frontend
          action: rebuild

  auth: 
    container_name: auth
    build: 
      context: auth
    networks:
      - app_network
    env_file: auth.env
    depends_on: 
      - postgres
    restart: on-failure

    develop: 
      watch: 
        - path: auth
          action: rebuild
    
  gorunner:
    container_name: gorunner
    build:
      context: ./langrunner
      dockerfile: Dockerfile.rest.golang
    environment:
      - SAFE_USERNAMES=gouser
      - RUN_TIMEOUT=30000
      - PORT=80
    networks:
      - app_network
      
    develop:
      watch: 
        - path: langrunner
          action: rebuild

  pyrunner:
    container_name: pyrunner
    build:
      context: ./langrunner
      dockerfile: Dockerfile.rest.python
    environment:
      - SAFE_USERNAMES=gouser
      - RUN_TIMEOUT=30000
      - PORT=80
    networks:
      - app_network

    develop:
      watch: 
        - path: langrunner
          action: rebuild

networks:
  app_network:
    driver: bridge

volumes:
  coderunner-logs:
  coderunner-data:
