# Build stage
FROM golang:1.23

# Set working directory
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN go build -o ./cliApp ./cmd/cli/main.go 

# Run the binary
ENTRYPOINT ["./cliApp"]
