FROM golang:1.23

WORKDIR /init

COPY ./scripts/init_container.sh ./
RUN bash ./init_container.sh

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o ./server ./cmd/rest

ENTRYPOINT ["./server"]
